parameters:
    hype_mailchimp.class: Hype\MailchimpBundle\Mailchimp\MailChimp

services:
    hype_mailchimp:
      class: '%hype_mailchimp.class%'
      arguments: ['%hypemailchimp.config%']
      public: true
